apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aws-cert
  namespace: awsdevops
spec:
  secretName: aws-key
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: admin.hccloudtech.online
  dnsNames:
    - testy.hccloudtech.online
    - apitest.hccloudtech.online
